/**
 * The name a timetable gets when the user does not give it one.
 *
 * Naming is optional. A blank name becomes the word for a timetable in the
 * user's language followed by the lowest positive number that is not already
 * taken — "Timetable1", "Timetable2"; "Расписание1"; "Stundenplan1". Taken
 * means held by the active timetable or by any archived one, compared without
 * regard to case or surrounding spaces, so "timetable1 " counts as
 * "Timetable1". A number freed by deleting its timetable is used again.
 *
 * Only generated names have to be unique. A name the user typed is theirs, and
 * two timetables both called "SoSe26" is a choice rather than a collision.
 *
 * Pure, and applied only when a timetable is actually created — never when the
 * setup flow merely opens — so abandoning the flow reserves nothing, and two
 * blank creations in a row get two different numbers.
 */
export function nextDefaultTimetableName(base: string, existingNames: readonly string[]): string {
  const stem = base.trim();
  // Nothing to number: the caller refuses a blank name rather than inventing "1".
  if (!stem) return "";
  const taken = new Set(existingNames.map((name) => name.trim().toLocaleLowerCase()));

  // Terminates: `taken` is finite, so some number past its size is free.
  for (let number = 1; ; number++) {
    const candidate = `${stem}${number}`;
    if (!taken.has(candidate.toLocaleLowerCase())) return candidate;
  }
}

/**
 * The name an *imported* timetable is given when that name is already on the
 * device: the same name with the lowest free `(n)` after it.
 *
 * "SoSe26", "SoSe26 (1)", "SoSe26 (2)". Importing the same file three times
 * otherwise produces three rows all reading "SoSe26", which is safe — they are
 * three separate timetables with separate ids — and unusable, because the list
 * is how the user tells them apart and it said the same thing three times. A
 * file in a chat is easy to tap twice.
 *
 * ## Why only imports
 *
 * A name the user *typed* is theirs, and two timetables both called "SoSe26" is
 * a choice the product deliberately allows — renaming one because the other
 * exists would be the app overruling them. An import is the one case where the
 * name was not a choice at all: it came out of a file, the user never typed it,
 * and the copy they are making is genuinely a second thing that needs telling
 * apart from the first. So `createTimetable` and `restoreArchivedTimetable` are
 * untouched, and only `importTimetableSnapshot` calls this.
 *
 * The file is not modified either. This is the name of the *local copy*; the
 * `.temelo` on disk still says what it always said.
 *
 * ## The comparison
 *
 * Taken means held by the active timetable or by any archived one, compared
 * trimmed and case-folded — the same normalization `nextDefaultTimetableName`
 * uses, so "sose26 " blocks "SoSe26" for both of them and the two functions
 * cannot disagree about what "already exists" means.
 *
 * The base is the imported name exactly as it arrived, suffix and all. A file
 * called "SoSe26 (1)" landing beside a "SoSe26 (1)" becomes "SoSe26 (1) (1)",
 * which is ugly and correct: re-basing it onto "SoSe26" would mean guessing
 * that a name ending in a number in brackets was generated by this rule rather
 * than typed by a person, and that guess is wrong exactly when it matters.
 *
 * `maxLength` is the stored limit, counted in code points. The *base* is
 * shortened to make room for the suffix rather than the suffix being dropped,
 * because a name trimmed by four characters is still recognisable and a name
 * that silently collides again is not. When the limit cannot fit even a
 * one-digit suffix — a limit under five — the candidate is returned as it is
 * and the caller's own normalization has the last word.
 */
export function nextAvailableImportName(
  name: string,
  existingNames: readonly string[],
  maxLength?: number,
): string {
  const base = name.trim();
  // Nothing to number, and nothing this could say about it that the caller's
  // own normalization does not already say better.
  if (!base) return name;

  const taken = new Set(existingNames.map((existing) => existing.trim().toLocaleLowerCase()));
  if (!taken.has(base.toLocaleLowerCase())) return base;

  // Terminates: `taken` is finite, so some number past its size is free.
  for (let number = 1; ; number++) {
    const suffix = ` (${number})`;
    const room = maxLength === undefined ? undefined : maxLength - [...suffix].length;
    // The base loses characters, not the suffix: a name four characters
    // shorter is still recognisable, and one that collides again is not.
    const stem = room === undefined || room < 1 ? base : [...base].slice(0, room).join("").trimEnd();
    const candidate = `${stem.length > 0 ? stem : base}${suffix}`;
    if (!taken.has(candidate.toLocaleLowerCase())) return candidate;
  }
}
